modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/RFToolsUtility/issues"
displayURL="http://github.com/McJtyMods/RFToolsUtility/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="rftoolsutility"
version="${file.jarVersion}"
displayName="RFToolsUtility"
#updateJSONURL="http://myurl.me/" #optional
description='''
Generic RFTools utilities
'''
[[dependencies.rftoolsutility]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsutility]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4.1.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.rftoolsutility]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.15-1.1.6,)"
    ordering="AFTER"
    side="BOTH"